// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOTIONPROTOCOL_MOTIONPROTOCOL_H_
#define FLATBUFFERS_GENERATED_MOTIONPROTOCOL_MOTIONPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace MotionProtocol {

struct Remote;
struct RemoteBuilder;

struct Message;
struct MessageBuilder;

enum MessageType : int8_t {
  MessageType_UNKNOWN = 0,
  MessageType_REMOTE = 1,
  MessageType_MIN = MessageType_UNKNOWN,
  MessageType_MAX = MessageType_REMOTE
};

inline const MessageType (&EnumValuesMessageType())[2] {
  static const MessageType values[] = {
    MessageType_UNKNOWN,
    MessageType_REMOTE
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[3] = {
    "UNKNOWN",
    "REMOTE",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType_UNKNOWN, MessageType_REMOTE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

struct Remote FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoteBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MENU_DOWN = 4,
    VT_SELECT = 6,
    VT_MENU_UP = 8,
    VT_TOGGLE_BOTTOM = 10,
    VT_TOGGLE_TOP = 12,
    VT_TOGGLE1 = 14,
    VT_TOGGLE2 = 16,
    VT_MODE = 18,
    VT_RLR = 20,
    VT_RFB = 22,
    VT_RT = 24,
    VT_LLR = 26,
    VT_LFB = 28,
    VT_LT = 30
  };
  int16_t menu_down() const {
    return GetField<int16_t>(VT_MENU_DOWN, 0);
  }
  int16_t select() const {
    return GetField<int16_t>(VT_SELECT, 0);
  }
  int16_t menu_up() const {
    return GetField<int16_t>(VT_MENU_UP, 0);
  }
  bool toggle_bottom() const {
    return GetField<uint8_t>(VT_TOGGLE_BOTTOM, 0) != 0;
  }
  bool toggle_top() const {
    return GetField<uint8_t>(VT_TOGGLE_TOP, 0) != 0;
  }
  bool toggle1() const {
    return GetField<uint8_t>(VT_TOGGLE1, 0) != 0;
  }
  bool toggle2() const {
    return GetField<uint8_t>(VT_TOGGLE2, 0) != 0;
  }
  int8_t mode() const {
    return GetField<int8_t>(VT_MODE, 0);
  }
  int8_t rlr() const {
    return GetField<int8_t>(VT_RLR, 0);
  }
  int8_t rfb() const {
    return GetField<int8_t>(VT_RFB, 0);
  }
  uint8_t rt() const {
    return GetField<uint8_t>(VT_RT, 0);
  }
  int8_t llr() const {
    return GetField<int8_t>(VT_LLR, 0);
  }
  int8_t lfb() const {
    return GetField<int8_t>(VT_LFB, 0);
  }
  uint8_t lt() const {
    return GetField<uint8_t>(VT_LT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_MENU_DOWN, 2) &&
           VerifyField<int16_t>(verifier, VT_SELECT, 2) &&
           VerifyField<int16_t>(verifier, VT_MENU_UP, 2) &&
           VerifyField<uint8_t>(verifier, VT_TOGGLE_BOTTOM, 1) &&
           VerifyField<uint8_t>(verifier, VT_TOGGLE_TOP, 1) &&
           VerifyField<uint8_t>(verifier, VT_TOGGLE1, 1) &&
           VerifyField<uint8_t>(verifier, VT_TOGGLE2, 1) &&
           VerifyField<int8_t>(verifier, VT_MODE, 1) &&
           VerifyField<int8_t>(verifier, VT_RLR, 1) &&
           VerifyField<int8_t>(verifier, VT_RFB, 1) &&
           VerifyField<uint8_t>(verifier, VT_RT, 1) &&
           VerifyField<int8_t>(verifier, VT_LLR, 1) &&
           VerifyField<int8_t>(verifier, VT_LFB, 1) &&
           VerifyField<uint8_t>(verifier, VT_LT, 1) &&
           verifier.EndTable();
  }
};

struct RemoteBuilder {
  typedef Remote Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_menu_down(int16_t menu_down) {
    fbb_.AddElement<int16_t>(Remote::VT_MENU_DOWN, menu_down, 0);
  }
  void add_select(int16_t select) {
    fbb_.AddElement<int16_t>(Remote::VT_SELECT, select, 0);
  }
  void add_menu_up(int16_t menu_up) {
    fbb_.AddElement<int16_t>(Remote::VT_MENU_UP, menu_up, 0);
  }
  void add_toggle_bottom(bool toggle_bottom) {
    fbb_.AddElement<uint8_t>(Remote::VT_TOGGLE_BOTTOM, static_cast<uint8_t>(toggle_bottom), 0);
  }
  void add_toggle_top(bool toggle_top) {
    fbb_.AddElement<uint8_t>(Remote::VT_TOGGLE_TOP, static_cast<uint8_t>(toggle_top), 0);
  }
  void add_toggle1(bool toggle1) {
    fbb_.AddElement<uint8_t>(Remote::VT_TOGGLE1, static_cast<uint8_t>(toggle1), 0);
  }
  void add_toggle2(bool toggle2) {
    fbb_.AddElement<uint8_t>(Remote::VT_TOGGLE2, static_cast<uint8_t>(toggle2), 0);
  }
  void add_mode(int8_t mode) {
    fbb_.AddElement<int8_t>(Remote::VT_MODE, mode, 0);
  }
  void add_rlr(int8_t rlr) {
    fbb_.AddElement<int8_t>(Remote::VT_RLR, rlr, 0);
  }
  void add_rfb(int8_t rfb) {
    fbb_.AddElement<int8_t>(Remote::VT_RFB, rfb, 0);
  }
  void add_rt(uint8_t rt) {
    fbb_.AddElement<uint8_t>(Remote::VT_RT, rt, 0);
  }
  void add_llr(int8_t llr) {
    fbb_.AddElement<int8_t>(Remote::VT_LLR, llr, 0);
  }
  void add_lfb(int8_t lfb) {
    fbb_.AddElement<int8_t>(Remote::VT_LFB, lfb, 0);
  }
  void add_lt(uint8_t lt) {
    fbb_.AddElement<uint8_t>(Remote::VT_LT, lt, 0);
  }
  explicit RemoteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Remote> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Remote>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Remote> CreateRemote(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t menu_down = 0,
    int16_t select = 0,
    int16_t menu_up = 0,
    bool toggle_bottom = false,
    bool toggle_top = false,
    bool toggle1 = false,
    bool toggle2 = false,
    int8_t mode = 0,
    int8_t rlr = 0,
    int8_t rfb = 0,
    uint8_t rt = 0,
    int8_t llr = 0,
    int8_t lfb = 0,
    uint8_t lt = 0) {
  RemoteBuilder builder_(_fbb);
  builder_.add_menu_up(menu_up);
  builder_.add_select(select);
  builder_.add_menu_down(menu_down);
  builder_.add_lt(lt);
  builder_.add_lfb(lfb);
  builder_.add_llr(llr);
  builder_.add_rt(rt);
  builder_.add_rfb(rfb);
  builder_.add_rlr(rlr);
  builder_.add_mode(mode);
  builder_.add_toggle2(toggle2);
  builder_.add_toggle1(toggle1);
  builder_.add_toggle_top(toggle_top);
  builder_.add_toggle_bottom(toggle_bottom);
  return builder_.Finish();
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_REMOTE = 6
  };
  MotionProtocol::MessageType type() const {
    return static_cast<MotionProtocol::MessageType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const MotionProtocol::Remote *remote() const {
    return GetPointer<const MotionProtocol::Remote *>(VT_REMOTE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_REMOTE) &&
           verifier.VerifyTable(remote()) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(MotionProtocol::MessageType type) {
    fbb_.AddElement<int8_t>(Message::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_remote(::flatbuffers::Offset<MotionProtocol::Remote> remote) {
    fbb_.AddOffset(Message::VT_REMOTE, remote);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MotionProtocol::MessageType type = MotionProtocol::MessageType_UNKNOWN,
    ::flatbuffers::Offset<MotionProtocol::Remote> remote = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_remote(remote);
  builder_.add_type(type);
  return builder_.Finish();
}

inline const MotionProtocol::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<MotionProtocol::Message>(buf);
}

inline const MotionProtocol::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MotionProtocol::Message>(buf);
}

inline bool VerifyMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MotionProtocol::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MotionProtocol::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MotionProtocol::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MotionProtocol::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MotionProtocol

#endif  // FLATBUFFERS_GENERATED_MOTIONPROTOCOL_MOTIONPROTOCOL_H_
